#!/bin/bash

# Install Homebrew (if necessary)
which brew > /dev/null || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Tap some (non-default) kegs; needs -n1 since tap only takes one keg per call
if [ -e kegs.txt ]; then
    xargs -n1 brew tap < kegs.txt
fi

# Install packages from Homebrew
if [ -e /packages.txt ]; then
    xargs brew install < packages.txt
fi

# Start any necessary services
if [ -e start-services.txt ]; then
    xargs -n1 brew services start < start-services.txt
fi

# Install casks from Homebrew
if [ -e casks.txt ]; then
    xargs brew cask install < casks.txt
fi
